
cache: pip
sudo: false

stage_generic: &stage_linux
  os: linux
  language: python
  python: 3.8
  env:
    - QISKIT_IBM_USE_STAGING_CREDENTIALS=true
    - QISKIT_IBM_DEVICE_STAGING=ibmq_qasm_simulator
  install:
    - pip install -U -r requirements.txt
    - pip install -U -r requirements-dev.txt

###############################################################################
# Stage-related definitions
###############################################################################

# Define the order of the stages.
stages:
  - staging_test
  - production_test

jobs:
  include:
    - stage: staging_test
      <<: *stage_linux
      if: type = pull_request
      script:
        - make update && make test
      after_script:
        - make cleanup

    - stage: staging_test
      <<: *stage_linux
      if: branch = master AND type = push
      script:
        - make update && make test && make publish
      after_failure:
        - make cleanup

    - stage: production_test
      <<: *stage_linux
      if: branch = master AND type = push
      env:
        - QISKIT_IBM_USE_STAGING_CREDENTIALS=false
      script:
        - make update && make test && make publish
      after_failure:
        - make cleanup
