from qiskit_primitives.sampler import Sampler


def main(backend, user_messenger,
         circuits,
         circuit_indices,
         parameters=None,
         parameter_values=None,
         skip_transpilation=False,
         run_options=None
         ):
    
    """Sample distributions generated by given circuits executed on the target backend.
    
    Parameters:
        backend (ProgramBackend): Qiskit backend instance.
        user_messenger (UserMessenger): Used to communicate with the program user.
        circuits: (QuantumCircuit or list): A single list of QuantumCircuits.
        parameters (list): Parameters of the quantum circuits.
        circuit_indices (list): Indexes of the circuits to evaluate.
        parameter_values (list): Concrete parameters to be bound.
        skip_transpilation (bool): Skip transpiling of circuits, default=False.
        run_options (dict): A collection of kwargs passed to backend.run().

    Returns:
        dict: A dictionary with quasi-probabilities and metadata.
    """
    sampler = Sampler(
        backend=backend,
        circuits=circuits,
        parameters=parameters,
        skip_transpilation=skip_transpilation
    )

    run_options = run_options or {}
    raw_result = sampler(
        circuit_indices=circuit_indices,
        parameter_values=parameter_values,
        **run_options)

    result = raw_result.__dict__
    result["quasi_dists"] = [dist.binary_probabilities() for dist in result["quasi_dists"]]

    return result
