from dataclasses import asdict

from qiskit.quantum_info.primitives.sampler.sampler import Sampler


def main(backend, user_messenger,
         circuits,
         parameters=None,
         circuit_indices=None,
         parameter_values=None,
         transpile_options=None,
         run_options=None,
         skip_transpilation=False
         ):
    
    """Sample distributions generated by given circuits executed on the target backend.
    
    Parameters:
        backend (ProgramBackend): Qiskit backend instance.
        user_messenger (UserMessenger): Used to communicate with the program user.
        circuits: (QuantumCircuit or list): A single list of QuantumCircuits.
        parameters (list): Parameters of the quantum circuits.
        circuit_indices (list): Indexes of the circuits to evaluate.
        parameter_values (list): Concrete parameters to be bound.
        transpile_options (dict): A collection of kwargs passed to transpile().
        run_options (dict): A collection of kwargs passed to backend.run().
        skip_transpilation (bool): Skip transpiling of circuits, default=False.

    Returns:
        dict: A dictionary with quasiprobabilities, and mitigation_overhead keys.
    """
    sampler = Sampler(
        backend=backend,
        circuits=circuits,
        parameters=parameters,
        skip_transpilation=False
    )
    if not skip_transpilation and transpile_options:
        sampler.set_transpile_options(**transpile_options)

    run_options = run_options or {}
    raw_result = sampler(
        circuits=circuit_indices,
        parameters=parameter_values,
        **run_options)

    result = asdict(raw_result)
    result["quasi_dists"] = [dist.binary_probabilities() for dist in result["quasi_dists"]]

    return result
